### PR TITLE
feat: allow use with custom federation plugin

### PR DESCRIPTION
**Pull request by justLuiz**
this commit allow users specifies a custom plugin: ex with NextFederationPlugin
```
    new NextFederationPlugin({}),
    new ModuleFederationTypesPlugin({
      federationPluginName: 'NextFederationPlugin'
    }),
```
solves: #34

### CODE REVIEW

**Comment by dhalbrook** [comment]
Funny, I was busy doing the same thing: https://github.com/cloudbeds/webpack-module-federation-types-plugin/pull/36

**Comment by steven-prybylynskyi** [comment]
Indeed :)
#36 was merged already

and the option's name was changed to `moduleFederationPluginName`

Thanks guys for the PRs

**Comment by dhalbrook** [comment]
Thanks Steven!

**Comment by steven-prybylynskyi** [comment]
Thx for the contribution

Released v1.14.0

**Pull request closed without merging**
